### ISSUE TITLE
Seems inflexable

### ISSUE THREAD

**Issue by belldandu** [TheRealAksel/structjs#2]
I have to call struct in order to change the format. which leads to extra code when you need to pack and unpack several times using different methods.

Why didn't you stick to having the fmt variable being a part of the function calls that are under the struct class like python?

https://docs.python.org/3/library/struct.html

**Comment by lyngklip** [comment]
The thing about struct is that it evaluates the format string only once and you can use the returned object multiple times both for packing and unpacking. If you find that you only use a format string once, then you may object to creating a struct only to apply it once and then discard it. In my opinion that is however the more flexible option and it's not hard to write a function that does exactly that.

edit:
The function calls in Python that take a format string are just that: functions. However Python also offer the possibility to make a Struct object from a format string. The methods belonging to the Struct object do not take a format string.

https://docs.python.org/3/library/struct.html#struct.Struct

edit:
I have added functions pack, unpack, pack_into, unpack_from, and iter_unpack to structjs.

edit:
I commented them out, I just don't like them around.

**Comment by lyngklip** [comment]
The module now emulates Python more closely, and thus I consider this issue closed.
